### ISSUE TITLE
June 2019 Lesson Release checklist

### ISSUE THREAD

**Issue by fmichonneau** [datacarpentry/geospatial-workshop#41]
If your Maintainer team has decided not to participate in the [June 2019 lesson release](https://carpentries.topicbox.com/groups/maintainers/T61c75ac1a8a89538/timeline-and-process-for-june-lesson-release), please close this issue.

To have this lesson included in the 18 June 2019 release, please confirm that the following items are true:

- [x] Call out boxes (exercises, discussions, tips, etc) render correctly
- [x] Setup instructions are up-to-date, correct, clear, and complete
- [x] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [x] Some Instructor notes are provided
- [x] Lesson links work as expected

When all checkboxes above are completed, this lesson will be added to the 18 June lesson release. Please leave a comment on carpentries/lesson-infrastructure#26 or contact Erin Becker with questions (ebecker@carpentries.org).

**Comment by ErinBecker** [comment]
Pinging the CAC @annefou, @arthur-e, @chris-prener, @jhollist, @jsta, @lwasser, @mdsumner, @MicheleTobias, @mapninja - there shouldn't be any large changes required for this repo, but depending on changes made to the individual lesson repos, there may be some updates needed to setup and install instructions. Any volunteers to check over this repo and make sure things are ready to go before the release in June?

**Comment by ErinBecker** [comment]
Hi all (@annefou, @arthur-e, @chris-prener, @jhollist, @jsta, @lwasser, @mdsumner, @MicheleTobias, @mapninja) - can anyone confirm whether there are any changes needed to this repo to keep it up to date with other Geospatial lessons that are being released this month?

**Comment by chris-prener** [comment]
I have some edits to make to the install instructions that I can make tomorrow AM @ErinBecker

**Comment by chris-prener** [comment]
OK - the setup instructions have been updated in #43, the call out boxes render correctly, and there are at least some instructor notes.

A number of the other points aren't really relevant for this since its just the overview lesson. Any thoughts on other areas that need to be addressed @ErinBecker and/or @fmichonneau?

**Comment by ErinBecker** [comment]
Thanks @chris-prener  - I just checked the links and everything seems to be in order. I've deleted the irrelevant checklist items and checked off the one for links. I think we're good to go here!

**Comment by chris-prener** [comment]
Thanks @ErinBecker!

**Comment by lwasser** [comment]
i don't have anything to add @ErinBecker

**Comment by fmichonneau** [comment]
Released! :tada: https://doi.org/10.5281/zenodo.3260290
