### ISSUE TITLE
Lesson release checklist

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/geospatial-workshop#7]
## Lesson Release checklist

**For each lesson release, copy this checklist to an issue and check off
during preparation for release**

Scheduled Freeze Date:   2018-06-13
Scheduled Release Date:  2018-06-15  

Checklist of tasks to complete before release:

- [ ] check for typos
- [x] check that the setup instructions are up to date (e.g., update version numbers)
- [x] check that data is available and mentions of the data in the lessons are accurate
- [ ] check that the instructor guide is up to date with the content of the lessons
- [ ] check that all the links within the lessons work (this should be automated)
- [ ] check that languge is clear and free of idioms and colloquialisms
- [ ] update README as needed
- [ ] check that contributor guidelines are clear and consistent
- [x] clean up files (e.g. delete deprecated files, insure filenames are consistent)
- [ ] update the release notes (NEWS)
- [ ] tag release on GitHub

**Comment by ErinBecker** [comment]
I deleted checklist items that don't apply to this repo - as they are meant for the lesson repos.
